management.sch: IA-Ames_20250122 (generated by CSIP Tue Jun 02 13:31:34 MDT 2026)
                          NAME NUMB_OPS NUMB_AUTO OP_TYP        MON        DAY     HU_SCH     OP_DATA1     OP_DATA2     OP_DATA3
                        mgt_01      141         0
                                                    till          5          1          0     tandemrg         null            0
                                                    till          5          3          0      fldcult         null            0
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2009
                                                    till          5         10          0     tandemrg         null            0
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    till          5         13          0      fldcult         null            0
                                                    plnt          5         15          0         soyb         null            0
                                                    harv         10          7          0         soyb        grain            0
                                                    kill         10          7          0         soyb         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2010
                                                    till          5          1          0     tandemrg         null            0
                                                    till          5          3          0      fldcult         null            0
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2011
                                                    till          5         10          0     tandemrg         null            0
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    till          5         13          0      fldcult         null            0
                                                    plnt          5         15          0         soyb         null            0
                                                    harv         10          7          0         soyb        grain            0
                                                    kill         10          7          0         soyb         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2012
                                                    till          5          1          0     tandemrg         null            0
                                                    till          5          3          0      fldcult         null            0
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2013
                                                    till          5         10          0     tandemrg         null            0
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    till          5         13          0      fldcult         null            0
                                                    plnt          5         15          0         soyb         null            0
                                                    harv         10          7          0         soyb        grain            0
                                                    kill         10          7          0         soyb         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2014
                                                    till          5          1          0     tandemrg         null            0
                                                    till          5          3          0      fldcult         null            0
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2015
                                                    till          5         10          0     tandemrg         null            0
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    till          5         13          0      fldcult         null            0
                                                    plnt          5         15          0         soyb         null            0
                                                    harv         10          7          0         soyb        grain            0
                                                    kill         10          7          0         soyb         null            0
                                                    till         10          9          0     dkchmtil         null            0
                                                    skip          0          0          0         null         null            0  # 2016
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    skip          0          0          0         null         null            0  # 2017
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    plnt          5         15          0         soyb         null            0
                                                    harv          9         30          0         soyb        grain            0
                                                    kill          9         30          0         soyb         null            0
                                                    skip          0          0          0         null         null            0  # 2018
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    skip          0          0          0         null         null            0  # 2019
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    plnt          5         15          0         soyb         null            0
                                                    harv          9         30          0         soyb        grain            0
                                                    kill          9         30          0         soyb         null            0
                                                    skip          0          0          0         null         null            0  # 2020
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    skip          0          0          0         null         null            0  # 2021
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    plnt          5         15          0         soyb         null            0
                                                    harv          9         30          0         soyb        grain            0
                                                    kill          9         30          0         soyb         null            0
                                                    skip          0          0          0         null         null            0  # 2022
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    skip          0          0          0         null         null            0  # 2023
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    plnt          5         15          0         soyb         null            0
                                                    harv          9         30          0         soyb        grain            0
                                                    kill          9         30          0         soyb         null            0
                                                    skip          0          0          0         null         null            0  # 2024
                                                    fert          5          3          0         mi_n       inject       78.460
                                                    fert          5          3          0         mi_p       inject       33.626
                                                    plnt          5          5          0         corn         null            0
                                                    fert          6          2          0         mi_n    broadcast      140.106
                                                    harv         10          7          0         corn        grain            0
                                                    kill         10          7          0         corn         null            0
                                                    skip          0          0          0         null         null            0  # 2025
                                                    fert          5         12          0         mi_n       inject       11.209
                                                    fert          5         12          0         mi_p       inject       33.626
                                                    plnt          5         15          0         soyb         null            0
                                                    harv          9         30          0         soyb        grain            0
                                                    kill          9         30          0         soyb         null            0
                                                    skip          0          0          0         null         null            0  # 1
